preload = ../../usr/share/hypr/wall2.png
# Set to all monitors (leave monitor name empty)
wallpaper = , ../../usr/share/hypr/wall2.png
# OR set for a specific monitor (find names via 'hyprctl monitors')
# wallpaper = monitor1, /path/to/your/image.png
